Update build-cmusicai-mac.yml

diff --git a/.github/workflows/build-cmusicai-mac.yml b/.github/workflows/build-cmusicai-mac.yml
--- a/.github/workflows/build-cmusicai-mac.yml
+++ b/.github/workflows/build-cmusicai-mac.yml
@@ -100,6 +100,13 @@ jobs:
                   cp ${GITHUB_WORKSPACE}/depends/x86_64-apple-darwin14/native/bin/x86_64-apple-darwin14-pagestuff unsigned-app-cmusicai/pagestuff
                   mv dist unsigned-app-cmusicai
                   
+                  # Debugging statements
+                  echo "Contents of native/bin:"
+                  ls -l ${GITHUB_WORKSPACE}/depends/x86_64-apple-darwin14/native/bin
+                  
+                  echo "Checking otool path:"
+                  which otool || echo "otool not found"
+                  
                   cd unsigned-app-cmusicai
                   find . | sort | tar --no-recursion --mode='u+rw,go+r-w,a+X' --owner=0 --group=0 -c -T - | gzip -9n > ${GITHUB_WORKSPACE}/release/cmusicai-${{ github.sha }}-osx-unsigned.tar.gz
                   
